[package]
name = "rustgym"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "leetcode/*"
]

[dependencies]
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
glob = "0.3"
colored = "2.0"
anyhow = "1.0"